import { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { FaArrowLeft, FaCalendarAlt, FaCreditCard, FaDumbbell, FaHistory, FaSignOutAlt, FaUser } from "react-icons/fa";
import { useAuth } from "../hooks/useAuth.js";
import { updateProfile } from "../services/profiles";
import { getMyAccount } from "../services/billing";
import { signOut } from "../services/auth";

const cls = "rounded-lg border border-border bg-background px-3 py-2 text-foreground outline-none transition-colors focus:border-brand focus:ring-2 focus:ring-brand/20";
export default function AccountPage() {
  const { user, profile, refreshProfile } = useAuth();
  const accountName = profile?.full_name || user.user_metadata?.full_name || user.user_metadata?.name || user.email?.split("@")[0] || "Alumno";
  const accountPhoto = user.user_metadata?.avatar_url || user.user_metadata?.picture;
  const accountInitials = accountName.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase() || "CT";
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  useEffect(() => { getMyAccount(user.id).then(setData).catch((e) => setError(e.message)); }, [user.id]);
  const save = async (event) => { event.preventDefault(); setBusy(true); setError(""); try { const form = new FormData(event.currentTarget); await updateProfile(user.id, { full_name: form.get("full_name"), phone: form.get("phone") || null, birth_date: form.get("birth_date") || null }); await refreshProfile(); setNotice("Perfil actualizado."); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <motion.main initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ duration: 0.3 }} className="min-h-screen bg-background px-4 pb-20 pt-28 text-foreground sm:px-6"><div className="mx-auto max-w-5xl"><header className="mb-6 flex flex-wrap items-center justify-between gap-3 border-b border-border pb-4"><a href="/" aria-label="Cano Team Martial Arts, ir al inicio" className="display text-xl font-bold text-foreground hover:text-brand">Cano Team <span className="text-brand">Martial Arts</span></a><a href="/" className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-border px-4 py-2 text-sm text-muted transition-colors hover:border-brand hover:text-foreground"><FaArrowLeft aria-hidden="true" />Volver al inicio</a></header><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex min-w-0 items-center gap-4"><span className="relative inline-flex h-14 w-14 shrink-0 items-center justify-center overflow-hidden rounded-full border border-brand/50 bg-brand-soft text-lg font-bold"><span>{accountInitials}</span>{accountPhoto&&<img src={accountPhoto} alt="" referrerPolicy="no-referrer" className="absolute inset-0 h-full w-full object-cover" onError={(event)=>{event.currentTarget.style.display="none";}}/>}</span><div className="min-w-0"><p className="eyebrow">Área privada</p><h1 className="display mt-1 truncate text-2xl font-bold sm:text-3xl">{accountName}</h1><p className="mt-1 truncate text-sm text-muted">{user.email}</p></div></div><div className="flex flex-wrap items-center gap-2">{profile?.role==="admin"&&<a href="/admin" className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-border px-4 py-2 text-sm text-muted transition-colors hover:border-brand hover:text-foreground">Panel administrativo</a>}<button onClick={() => void signOut()} className="inline-flex min-h-11 items-center gap-2 rounded-lg border border-border px-4 py-2 text-sm text-muted transition-colors hover:border-brand hover:text-foreground"><FaSignOutAlt aria-hidden="true" />Cerrar sesión</button></div></div>
  {error && <p role="alert" className="mt-5 rounded-lg bg-red-900/20 p-3 text-red-300">{error}</p>}
  <motion.section initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4, delay: 0.05 }} className="mt-7 rounded-2xl border border-border bg-surface p-5 sm:p-6"><h2 className="display flex items-center gap-3 text-xl font-semibold"><FaUser className="text-brand" aria-hidden="true" />Datos personales</h2><form onSubmit={save} className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><label className="text-sm">Nombre<input name="full_name" defaultValue={profile?.full_name ?? ""} required className={`${cls} mt-1 block min-h-11 w-full`} /></label><label className="text-sm">Teléfono<input name="phone" defaultValue={profile?.phone ?? ""} className={`${cls} mt-1 block min-h-11 w-full`} /></label><label className="text-sm">Fecha de nacimiento<input type="date" name="birth_date" defaultValue={profile?.birth_date ?? ""} className={`${cls} mt-1 block min-h-11 w-full`} /></label><button disabled={busy} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-brand px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-brand-strong disabled:opacity-60 sm:col-span-2 lg:col-span-3 lg:justify-self-start"><FaUser aria-hidden="true" />{busy ? "Guardando…" : "Guardar cambios"}</button></form>{notice && <p className="mt-3 text-sm text-green-300">{notice}</p>}</motion.section>
  {!data ? <p className="mt-6 animate-pulse text-muted">Cargando membresías y cuotas…</p> : <>
  <motion.section initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4, delay: 0.1 }} className="mt-8"><h2 className="display flex items-center gap-3 text-xl font-semibold"><FaDumbbell className="text-brand" aria-hidden="true" />Membresías y disciplinas</h2>{!data.memberships.length ? <p className="mt-3 rounded-xl border border-border bg-surface p-5 text-muted">Todavía no hay membresías asociadas a tu cuenta.</p> : <div className="mt-4 grid gap-4 sm:grid-cols-2">{data.memberships.map((m) => <motion.article key={m.id} whileHover={{ y: -2 }} className="rounded-2xl border border-border bg-surface p-5 transition-colors hover:border-brand"><h3 className="display text-lg font-semibold">{m.disciplines?.name ?? "Disciplina"}</h3><p className="mt-2 text-sm text-muted">{m.fee_plans?.name ?? "Plan"} · {m.fee_plans?.currency ?? ""} {m.fee_plans?.amount ?? ""} / {m.fee_plans?.billing_period ?? ""}</p><p className="mt-2 inline-flex items-center gap-2 text-sm"><FaCalendarAlt aria-hidden="true" className="text-brand" />{m.status} · Desde {m.start_date ?? "sin fecha"}</p></motion.article>)}</div>}</motion.section>
  <motion.section initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4, delay: 0.14 }} className="mt-8"><h2 className="display flex items-center gap-3 text-xl font-semibold"><FaCreditCard className="text-brand" aria-hidden="true" />Cuotas</h2>{!data.invoices.length ? <p className="mt-3 rounded-xl border border-border bg-surface p-5 text-muted">No hay cuotas generadas.</p> : <div className="mt-4 overflow-x-auto rounded-xl border border-border bg-surface"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-surface-2 text-xs uppercase tracking-wider text-muted"><tr>{["Período","Detalle","Importe","Vencimiento","Estado","Acción"].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{data.invoices.map((i)=><tr key={i.id} className="border-t border-border transition-colors hover:bg-surface-2"><td className="px-4 py-3">{i.period_month}/{i.period_year}</td><td className="px-4 py-3">{i.description}</td><td className="px-4 py-3">{i.currency} {i.amount}</td><td className="px-4 py-3">{i.due_date ?? "—"}</td><td className="px-4 py-3">{i.status}</td><td className="px-4 py-3"><button type="button" disabled={i.status === "paid" || i.status === "cancelled"} onClick={()=>setNotice("El flujo Payway requiere configurar una Edge Function y credenciales del proveedor antes de habilitar el pago.")} className="inline-flex min-h-10 items-center gap-2 whitespace-nowrap rounded-lg bg-brand px-3 py-2 text-xs font-semibold text-white transition-colors hover:bg-brand-strong disabled:cursor-not-allowed disabled:opacity-40"><FaCreditCard aria-hidden="true" />Pagar cuota</button></td></tr>)}</tbody></table></div>}</motion.section>
  <motion.section initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4, delay: 0.18 }} className="mt-8"><h2 className="display flex items-center gap-3 text-xl font-semibold"><FaHistory className="text-brand" aria-hidden="true" />Historial de pagos</h2>{!data.payments.length ? <p className="mt-3 rounded-xl border border-border bg-surface p-5 text-muted">No hay pagos registrados.</p> : <div className="mt-4 space-y-2">{data.payments.map(p=><motion.div key={p.id} whileHover={{ x: 2 }} className="flex flex-wrap justify-between gap-2 rounded-xl border border-border bg-surface p-4 text-sm transition-colors hover:border-brand"><span>{p.currency} {p.amount} · {p.provider ?? "—"}</span><span className="text-muted">{p.status} · {p.paid_at ?? p.created_at}</span></motion.div>)}</div>}</motion.section></>}</div></motion.main>;
}
