import { useEffect, useState } from "react";
import { useAuth } from "../hooks/useAuth.js";
import { updateProfile } from "../services/profiles";
import { getMyAccount } from "../services/billing";
import { signOut } from "../services/auth";

const cls = "rounded-lg border border-border bg-background px-3 py-2 text-foreground";
export default function AccountPage() {
  const { user, profile, refreshProfile } = useAuth();
  const [data, setData] = useState(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  useEffect(() => { getMyAccount(user.id).then(setData).catch((e) => setError(e.message)); }, [user.id]);
  const save = async (event) => { event.preventDefault(); setBusy(true); setError(""); try { const form = new FormData(event.currentTarget); await updateProfile(user.id, { full_name: form.get("full_name"), phone: form.get("phone") || null, birth_date: form.get("birth_date") || null }); await refreshProfile(); setNotice("Perfil actualizado."); } catch (e) { setError(e.message); } finally { setBusy(false); } };
  return <main className="min-h-screen bg-background px-5 pb-20 pt-28 text-foreground"><div className="mx-auto max-w-5xl"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm uppercase tracking-widest text-brand">Área privada</p><h1 className="display mt-2 text-3xl font-bold">Mi cuenta</h1></div><button onClick={() => void signOut()} className="rounded-lg border border-border px-4 py-2">Cerrar sesión</button></div>
  {error && <p role="alert" className="mt-5 rounded-lg bg-red-900/20 p-3 text-red-300">{error}</p>}
  <section className="mt-7 rounded-2xl border border-border bg-surface p-6"><h2 className="display text-xl font-semibold">Datos personales</h2><form onSubmit={save} className="mt-4 grid gap-4 sm:grid-cols-3"><label className="text-sm">Nombre<input name="full_name" defaultValue={profile?.full_name ?? ""} required className={`${cls} mt-1 block w-full`} /></label><label className="text-sm">Teléfono<input name="phone" defaultValue={profile?.phone ?? ""} className={`${cls} mt-1 block w-full`} /></label><label className="text-sm">Fecha de nacimiento<input type="date" name="birth_date" defaultValue={profile?.birth_date ?? ""} className={`${cls} mt-1 block w-full`} /></label><button disabled={busy} className="rounded-lg bg-brand px-4 py-2 font-semibold text-white sm:col-span-3 sm:justify-self-start">Guardar cambios</button></form>{notice && <p className="mt-3 text-sm text-green-300">{notice}</p>}</section>
  {!data ? <p className="mt-6 animate-pulse text-muted">Cargando membresías y cuotas…</p> : <>
  <section className="mt-7"><h2 className="display text-xl font-semibold">Membresías y disciplinas</h2>{!data.memberships.length ? <p className="mt-3 rounded-xl border border-border p-5 text-muted">Todavía no hay membresías asociadas a tu cuenta.</p> : <div className="mt-4 grid gap-4 md:grid-cols-2">{data.memberships.map((m) => <article key={m.id} className="rounded-2xl border border-border bg-surface p-5"><h3 className="font-semibold">{m.disciplines?.name ?? "Disciplina"}</h3><p className="mt-2 text-sm text-muted">{m.fee_plans?.name ?? "Plan"} · {m.fee_plans?.currency ?? ""} {m.fee_plans?.amount ?? ""} / {m.fee_plans?.billing_period ?? ""}</p><p className="mt-1 text-sm">Estado: {m.status} · Desde {m.start_date ?? "sin fecha"}</p></article>)}</div>}</section>
  <section className="mt-8"><h2 className="display text-xl font-semibold">Cuotas</h2>{!data.invoices.length ? <p className="mt-3 rounded-xl border border-border p-5 text-muted">No hay cuotas generadas.</p> : <div className="mt-4 overflow-x-auto rounded-xl border border-border"><table className="w-full text-left text-sm"><thead className="bg-surface text-muted"><tr>{["Período","Detalle","Importe","Vencimiento","Estado","Acción"].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{data.invoices.map((i)=><tr key={i.id} className="border-t border-border"><td className="px-4 py-3">{i.period_month}/{i.period_year}</td><td className="px-4 py-3">{i.description}</td><td className="px-4 py-3">{i.currency} {i.amount}</td><td className="px-4 py-3">{i.due_date ?? "—"}</td><td className="px-4 py-3">{i.status}</td><td className="px-4 py-3"><button type="button" disabled={i.status === "paid" || i.status === "cancelled"} onClick={()=>setNotice("El flujo Payway requiere configurar una Edge Function y credenciales del proveedor antes de habilitar el pago.")} className="rounded-lg bg-brand px-3 py-2 text-white disabled:opacity-40">Pagar cuota</button></td></tr>)}</tbody></table></div>}</section>
  <section className="mt-8"><h2 className="display text-xl font-semibold">Historial de pagos</h2>{!data.payments.length ? <p className="mt-3 rounded-xl border border-border p-5 text-muted">No hay pagos registrados.</p> : <div className="mt-4 space-y-2">{data.payments.map(p=><div key={p.id} className="flex flex-wrap justify-between gap-2 rounded-xl border border-border bg-surface p-4"><span>{p.currency} {p.amount} · {p.provider ?? "—"}</span><span>{p.status} · {p.paid_at ?? p.created_at}</span></div>)}</div>}</section></>}</div></main>;
}
